server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-register: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
